module SkelResolution = struct

(* OCaml module generated by the BNF converter *)

open AbsResolution

type result = string

let failure x = failwith "Undefined case." (* x discarded *)

let rec transIdent (x : ident) : result = match x with
    Ident string -> failure x


and transFormExp (x : formExp) : result = match x with
    PropName ident -> failure x
  | ConjExp (formexp0, formexp) -> failure x
  | DisjExp (formexp0, formexp) -> failure x


and transForm (x : form) : result = match x with
    Conj (form0, form) -> failure x
  | Disj (form0, form) -> failure x
  | Prop integer -> failure x



end
