(* show functions generated by the BNF converter *)

open AbsResolution

(* use string buffers for efficient string concatenations *)
type showable = Buffer.t -> unit

let show (s : showable) : string = 
    let init_size = 16 in (* you may want to adjust this *)
    let b = Buffer.create init_size in
    s b;
    Buffer.contents b
    
let emptyS : showable = fun buf -> ()

let c2s (c:char) : showable = fun buf -> Buffer.add_char buf c
let s2s (s:string) : showable = fun buf -> Buffer.add_string buf s

let ( >> ) (s1 : showable) (s2 : showable) : showable = fun buf -> s1 buf; s2 buf

let showChar (c:char) : showable = fun buf -> 
    Buffer.add_string buf ("'" ^ Char.escaped c ^ "'")

let showString (s:string) : showable = fun buf -> 
    Buffer.add_string buf ("\"" ^ String.escaped s ^ "\"")

let showList (showFun : 'a -> showable) (xs : 'a list) : showable = fun buf -> 
    let rec f ys = match ys with
        [] -> ()
      | [y] -> showFun y buf
      | y::ys -> showFun y buf; Buffer.add_string buf "; "; f ys 
    in
        Buffer.add_char buf '[';
        f xs;
        Buffer.add_char buf ']'


let showInt (i:int) : showable = s2s (string_of_int i)
let showFloat (f:float) : showable = s2s (string_of_float f)
let rec showIdent (Ident i) : showable = s2s "Ident " >> showString i


let rec showFormExp (e:formExp) : showable = match e with
       PropName ident -> s2s "PropName" >> c2s ' ' >> c2s '(' >> showIdent ident >> c2s ')'
  |    NegExp formexp -> s2s "NegExp" >> c2s ' ' >> c2s '(' >> showFormExp formexp >> c2s ')'
  |    DisjExp (formexp0, formexp) -> s2s "DisjExp" >> c2s ' ' >> c2s '(' >> showFormExp formexp0  >> s2s ", " >>  showFormExp formexp >> c2s ')'
  |    ConjExp (formexp0, formexp) -> s2s "ConjExp" >> c2s ' ' >> c2s '(' >> showFormExp formexp0  >> s2s ", " >>  showFormExp formexp >> c2s ')'
  |    ImplExp (formexp0, formexp) -> s2s "ImplExp" >> c2s ' ' >> c2s '(' >> showFormExp formexp0  >> s2s ", " >>  showFormExp formexp >> c2s ')'


and showForm (e:form) : showable = match e with
       Conj (form0, form) -> s2s "Conj" >> c2s ' ' >> c2s '(' >> showForm form0  >> s2s ", " >>  showForm form >> c2s ')'
  |    Disj (form0, form) -> s2s "Disj" >> c2s ' ' >> c2s '(' >> showForm form0  >> s2s ", " >>  showForm form >> c2s ')'
  |    Prop string -> s2s "Prop" >> c2s ' ' >> c2s '(' >> showString string >> c2s ')'
  |    Neg form -> s2s "Neg" >> c2s ' ' >> c2s '(' >> showForm form >> c2s ')'



